#!/bin/sh
# MacOSX only -
# Use install_name_tool to prefix any reference to a Qt library with
# @rpath, if not already like so.
# This is to make sure that the Qt libraries are always loaded from the
# application's bundle

doo(){
  echo "[fix_qt_refs] $@"
  "$@"
}
TARGET="$1"
QTBASE="$2"
REFS=`otool -L "$TARGET" | grep -e /Qt -e phonon | grep -v  @executable_path | grep -v @rpath | grep -v ':$' | awk '{ print $1 }' `
for r in $REFS ; do
  base=`echo $r | sed -e s@$QTBASE/@@g`
  doo install_name_tool -change "$r" "@rpath/$base" "$TARGET"
done
