/**
 * @~english
 * @taomoduledescription{Slides, Slides creation}
 *
* Commands create easily some basic slides.
 *
 * The Slides module defines commands that you can use to add some basic slides into
 * your presentations: @ref blank_slide, @ref title_slide, @ref section_slide,
 * @ref slide and more. You can add text bullets with symbols
 * like @ref ＊, @ref ‐ and @ref ＋. \n
 *
 * The slide layout and colors are grouped by themes. Each theme as a name,
 * for instance @c "Default" or @c "Keyboard". Selecting a theme is just the
 * matter of import the wanted theme with @ref import (except for "Default" theme)
 * and using the @ref theme function with the suitable value, before using
 * the slide commands. For example:
 @code
import Slides
import KeyboardTheme // Import "Keyboard" theme

// Show a top title slide with the default theme
toptitle_slide "My title slide",
    text "This shows the default theme"

// Change theme to "Keyboard"
theme "Keyboard"

slide "The Keyboard theme",
 *    * "Has a background picture"
 *    * "Is nicer than the default theme"
 @endcode
 *
 * The Slides module currently defines a default
 * one, which is black text on white backround and can be selected by setting
 * @ref theme to the "Default" value. See @ref theme for
 * details.
 *
 * In addition, the module exposes an interface so that
 * you can customize the appearance of your slides and
 * create your own themes easily (see the definition of the "Default" theme in
 * the default.xl file, which situated in the module directory).
 *
 * Slides are automatically scaled to the size of the display area.
 * Background pictures are automatically scaled to cover at least the display
 * area. A part of the background may disappear if the aspect ratio of the
 * display area is not the same as the aspect ratio of the picture.
 * All elements on the slide are drawn assuming that the slide is 1920x1080
 * pixels by default. This can be adjusted with @ref set_slide_size.
 * Use @p window_width and @p window_height to get the size of the
 * display area. Use @ref slide_width and @ref slide_height to get the size
 * of the slide.
 *
 * Here is a more complete example showing all the slide types with some
 * @ref transition_ft_wipe transitions (see Transitions module for more details).
 *
 * @include slides_en.ddd
 *
 * Here is a mosaic of all the pages generated by the above program:
 * @image html slides_en.png "Output from slides.ddd"
 *
 * @endtaomoduledescription{Slides}
 *
 * @~french
 * @taomoduledescription{Slides, Creation de Diapositives }
 *
 * Commandes pour créer facilement des présentations type "Powerpoint".
 *
 * Le module Slides fournit des commandes que vous pouvez utiliser pour
 * ajouter facilement des diapositives simples dans vos présentations : @ref blank_slide, @ref title_slide, @ref section_slide,
 * @ref slide et d'autres. Les puces de texte peuvent être affichées
 * en utilisant @ref ＊, @ref ‐ et @ref ＋.. \n
 *
 * Les couleurs et mises en pages sont regroupées par thèmes. Chaque thème a un
 * nom, par exemple @c "Default" or @c "Keyboard". L'utilisation se fait
 * grâce à  la commande @ref theme après avoir importer le thème correspondant dans votre présentation.
 * Par exemple :
 @code
import Slides
import KeyboardTheme // Importation du thème "Keyboard

// Diapositive avec un titre, style par défaut
toptitle_slide "Diapo de titre",
    text "Il s'agit du thème par défaut"

// Activation du thème "Keyboard"
theme "Keyboard"

slide "Le thème Keyboard",
 *    * "A une image de fond"
 *    * "Est plus beau que le thème par défaut"
 @endcode
 *
 * Le module Slides fournit un thème par défaut appelé "Default", qui est noir sur
 * fond blanc et qui peut être activé en utilisant <tt>theme "Default"</tt>. Cf. la
 * commande @ref theme pour plus de détails.
 *
 * Ce module fournit également des commandes simples pour vous permettre de modifier
 * efficacement l'apparence de vos présentations (polices, couleurs, etc.) et
 * créer ainsi vos propre thèmes (voir la définition du thème "Default"
 * dans le fichier default.xl situé dans le repertoire du module.
 *
 * Les diapositives peuvent se redimensionner automatiquement pour remplir
 * au mieux l'écran. Lorsque l'image de fond n'a pas le même rapport de
 * largeur et de hauteur que l'écran, une partie du fond est coupée de sorte
 * que l'image couvre quand même tout l'écran.
 * Par défaut tous les éléments d'une diapositive sont dessinés pour une
 * résolution de 1920x1080 pixels. Ceci peut être ajusté en appelant
 * @ref set_slide_size. Utlisez @p window_width et @p window_height pour
 * obtenir la taille de l'affichage. Utilisez @ref slide_width et
 * @ref slide_height pour obtenir la taille de la diapositive.
 *
 * Voici un exemple plus complet qui illustre différents types de diapositives définit dans ce
 * module, comprenant également une transition de type @ref transition_ft_wipe (voir le module Transitions pour plus de détails).
 *
 * @include slides_fr.ddd
 *
 * Voici une mosaïque des pages affichées par cet exemple :
 * @image html slides_fr.png "Mises en page de diapositives"
 *
 * @endtaomoduledescription{Slides}
 *
 * @~
 * @{
 */


/**
 * @~english
 * The name of the current theme.
 * The next command that creates a slide page will take into account the
 * value of this variable to select the appearance of the slide.
 * @~french
 * Le nom du thème courant.
 * La prochaine commande qui crée une diapositive utilisera la valeur de cette
 * variable pour sélectionner l'apparence de la page.
 */
text theme = "default";

/**
 * @~english
 * The width of the current slide.
 * @~french
 * La largeur de la diapositive courante.
 */
real slide_width = 1920.0;

/**
 * @~english
 * The height of the current slide.
 * @~french
 * La hauteur de la diapositive courante.
 */
real slide_height = 1080.0;


/**
 * @~english
 * Select a new theme for all subsequent slides
 * @p Theme is the name of the new theme to be applied.
 * For instance, the following code re-select the default theme.
@code
theme "default"
@endcode
 *
 * @~french
 * Choisit un nouveau thème pour les dispositives à  suivre.
 * @p Theme correspond au nom du nouveau thème à  appliquer.
 * Par exemple, le code suivant ré-applique le thème par défaut.
@code
theme "default"
@endcode
 *
 * @~
 * @see theme
 */
theme(Theme:text);


/**
 * @~english
 * Creates a slide without a title and story (only the background).
 * @p T corresponds to the page name.
 * Below, an example of blank slide using the default theme.
@code
blank_slide "Empty slide", false
@endcode
 * @~french
 * Créer une diapositive vide (uniquement le background).
 * @p T correspond au nom de la diapositive.
 * Ci-dessous, un exemple de diapositive vide utilisant le thème par défaut.
@code
blank_slide "Diapositive vide", false
@endcode
 */
blank_slide(T:text, Body:code);


/**
 * @~english
 * Creates a slide with title and picture content.
 * The slide title @a T is used as the page name.
 * @~french
 * Créer une diapositive avec un titre et une zone libre.
 * Le titre de la diapositive, @p T, est utilisé comme nom de page.
 */
picture_slide(T:text, Body:code);

/**
 * @~english
 * Creates a main title slide (one unique text area).
 * @p T corresponds to the main title and the page name.
 * Below, an example of a title slide using the default theme.
@code
// Show only title and nothing else
title_slide "Presentation title", false
@endcode
 * @~french
 * Créer une diapositive de titre principal (une seule zone de texte).
 * @p T correspond au titre principal et au nom de la page.
 * Ci-dessous, un exemple de diapositive de titre utilisant le thème par défaut.
@code
// Affiche le titre principal et rien d'autre
title_slide "Titre de la présentation", false
@endcode
 */
title_slide(T:text, Body:code);


/**
 * @~english
 * Creates an empty @ref title_slide.
 * @p T corresponds to the main title and the page name.
 * It is a shortcut to the following code :
@code
title_slide T, false
@endcode
 *
 * @~french
 * Créer une diapositive @ref title_slide vide.
 * @p T correspond au titre principal et au nom de la page.
 * Il s'agit d'un raccourci au code suivant :
@code
title_slide T, false
@endcode
 *
 */
title_slide(T:text);


/**
 * @~english
 * Creates a section slide (one unique text area).
 * @p T corresponds to the section title and the page name.
 * Below, an example of this type of slide using the default theme.
@code
// Show only section title and nothing else
section_slide "Section title", false
@endcode
 * @~french
 * Créer une diapositive de transition entre sections.
 * @p T correspond au titre de la section et au nom de la page.
 * Ci-dessous, un exemple de ce type de diapositive utilisant le thème par défaut.
@code
// Affiche le titre de la section et rien d'autre
section_slide "Titre de la section", false
@endcode
 */
section_slide(T:text, Body:code);


/**
 * @~english
 * Creates an empty @ref section_slide.
 * @p T corresponds to the section title and the page name.
 * It is a shortcut to the following code :
@code
section_slide T, false
@endcode
 *
 * @~french
 * Créer une diapositive @ref section_slide vide.
 * @p T correspond au titre de la section et au nom de la page.
 * Il s'agit d'un raccourci au code suivant :
@code
section_slide T, false
@endcode
 *
 */
section_slide(T:text);


/**
 * @~english
 * Creates a slide with a title at the top.
 * The slide title @p T is used as the page name.
 * Below, an example of this type of slide using the default theme.
@code
// Show only top title and nothing else
toptitle_slide "Slide title", false
@endcode
 *
 * @~french
 * Créer une diapositive avec un titre situé en haut.
 * Le titre de la diapositive, @p T, est utilisé comme nom de page.
 * Ci-dessous, un exemple de ce type de diapositive utilisant le thème par défaut.
@code
// Affiche le titre en haut et rien d'autre
toptitle_slide "Titre de la diapositive", false
@endcode
 */
toptitle_slide(T:text, Body:code);


/**
 * @~english
 * Creates a slide with title and picture content.
 * The slide title @p T is used as the page name.
 * Below, an example of this type of slide using the default theme.
@code
// Show a slide with a picture
picture_slide "Slide title",
    image 0, 0, 100%, 100%, "my_picture.png"
@endcode
 *
 * @~french
 * Créer une diapositive avec un titre et une zone libre pour afficher images, photos, animations.
 * Le titre de la diapositive, @p T, est utilisé comme nom de page.
 * Ci-dessous, un exemple de ce type de diapositive utilisant le thème par défaut.
@code
// Affiche une diapositive contenant une image
picture_slide "Titre de la diapositive",
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 *
 */
picture_slide(T:text, Body:code);


/**
 * @~english
 * Creates a slide with title and bullet points.
 * The slide title @p T is used as the page name.
 * Below, an example of this type of slide using the default theme.
@code
// Show a slide with some bullet points
slide "Slide title",
    *"First-level bullet"
    -"Second-level bullet"
    +"Third-level bullet"
@endcode
 * @~french
 * Créer une diapositive avec un titre et du texte.
 * Le titre de la diapositive, @p T, est utilisé comme nom de page.
 * Ci-dessous, un exemple de ce type de diapositive utilisant le thème par défaut.
@code
// Affiche une diapositive avec différentes puces de texte
picture_slide "Titre de la diapositive",
    *"Texte de premier niveau"
    -"Texte de second niveau"
    +"Texte de troisième niveau"
@endcode
 */
slide(T:text, Body:code);


/**
 * @~english
 * Show a main title on the slide.
 * The main title given as an argument will be displayed according to
 * the current applied theme.
 *
 * For instance:
@code
// Define a main title
main_title
    text "My main title"
@endcode
 * @~french
 * Affiche un titre principal sur une diapositive.
 * Le titre principal donné en argument sera affiché suivant le
 * thème courant appliqué.
 *
 * Par exemple :
@code
// Définit un titre principal.
main_title
    text "Mon titre principal"
@endcode
 */
main_title(Body:code);


/**
 * @~english
 * Show a section title on the slide.
 * The section title given as an argument will be displayed according to
 * the current applied theme.
 *
 * For instance:
@code
// Define a section title
section_title
    text "My section title"
@endcode
 * @~french
 * Affiche un titre de section sur une diapositive.
 * Le titre donné en argument sera affiché suivant le
 * thème courant appliqué.
 *
 * Par exemple :
@code
// Définit un titre de section.
section_title
    text "Mon titre de section"
@endcode
 */
section_title(Body:code);


/**
 * @~english
 * Show a title on the slide.
 * The title given as an argument will be displayed according to
 * the current applied theme.
 *
 * For instance:
@code
// Show a title on blank slide
blank_slide "Page name",
    title
        text "My slide title"
@endcode
 * @~french
 * Affiche un titre de section sur une diapositive.
 * Le titre donné en argument sera affiché suivant le
 * thème courant appliqué.
 *
 * Par exemple :
@code
// Affiche un titre sur une diapositive vide.
blank_slide "Page name",
    title
        text "Mon titre de diapositive"
@endcode
 */
title(Body:code);


subtitle(Body:code);


/**
 * @~english
 * Draw something in the background that must fill the screen.
 * The background given as an argument will be displayed with
 * a scaling adjusted as a function of the window size
 * to ensure that it always fills.
 * @p Depth is the depth where is situated the background.
 *
 * For instance, to use an image as background:
@code
// Define a background at a depth of -300
background -300,
    image 0, 0, 100%, 100%, "my_image.png"
@endcode
 * @~french
 * Affiche quelque chose en arrière-plan d'une diapositive.
 * L'arrière-plan donné en argument sera affiché avec
 * un redimensionnement dépendant de la taille de la fenêtre principale,
 * afin d'assurer qu'il remplisse toujours complement l'écran.
 * @p Depth est la profondeur où est situé l'arrière-plan.
 *
 * Par exemple, pour afficher une image en arrière-plan :
@code
// Place un arrière-plan à  une profondeur de -300 pixels.
background -300,
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 */
background(Depth:real, Body:code);


/**
 * @~english
 * Draw contents that must fit on the slide.
 * The content given as an argument will be displayed with
 * a scaling adjusted as a function of the window size
 * to ensure that it always fits.
 * @p Depth is the depth where is situated this content.
 *
 * For instance, to use an image as contents:
@code
// Show an image at a zero depth.
contents 0,
    image 0, 0, 100%, 100%, "my_image.png"
@endcode
 * @~french
 * Affiche du contenu divers sur une diapositive.
 * Le contenu donné en argument sera affiché avec
 * un redimensionnement dépendant de la taille de la fenêtre principale,
 * afin d'assurer qu'il s'adapte toujours à  l'écran.
 * @p Depth est la profondeur où est situé le contenu.
 *
 * Par exemple, pour afficher une image :
@code
// Place une image à  une profondeur zéro.
contents 0,
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 */
contents(Depth:real, Body:code);


/**
 * @~english
 * Define a box for picture, photos, animations on the slide.
 * This box will be displayed according to
 * the current applied theme (by default, at the bottom of the slide).
 *
 * For instance:
@code
// Show an image in the picture box
picture
    image 0, 0, 100%, 100%, "my_image.png"
@endcode
 * @~french
 * Définit une boîte où placer images, photos, animation sur une diapositive.
 * Cette boîte sera affichée suivant le thème courant appliqué
 *(par défaut en bas de la diapositive).
 *
 * Par exemple :
@code
// Affiche une image dans la boîte
picture
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 */
picture(Body:code);


/**
 * @~english
 * Define a box where to put bullet points.
 * This box will be displayed according to
 * the current applied theme (by default, somewhere in the middle).
 *
 * For instance:
@code
// Show some bullet points
story
    *"First-level bullet"
    *"First-level bullet"
    -"Second-level bullet"
@endcode
 * @~french
 * Définit une boîte où placer des puces de textes.
 * Cette boîte sera affichée suivant le thème courant appliqué (par défaut,
 * quelque part au milieu de la diapositive).
 *
 * Par exemple :
@code
// Affiche plusieurs puces de textes
story
    *"Puce de premier niveau"
    *"Puce de premier niveau"
    -"Puce de second niveau"
@endcode
 */
story(Body:code);


/**
 * @~english
 * Define a column at the left of the slide where to put bullet points.
 * This column will be displayed according to
 * the current applied theme (by default, somewhere in the left).
 *
 * For instance:
@code
// Show some bullet points at the left
left_column
    *"First-level bullet"
    *"First-level bullet"
    -"Second-level bullet"
@endcode
 * @~french
 * Définit une colonne à  gauche de la diapositive où placer des puces de textes.
 * Cette colonne sera affichée suivant le thème courant appliqué (par défault,
 * quelque part à gauche de la diapositive).
 *
 * Par exemple :
@code
// Affiche plusieurs puces de textes à gauche
left_column
    *"Puce de premier niveau"
    *"Puce de premier niveau"
    -"Puce de second niveau"
@endcode
 */
left_column(Body:code);


/**
 * @~english
 * Define a column at the right of the slide where to put bullet points.
 * This column will be displayed according to
 * the current applied theme (by default, somewhere in the right).
 *
 * For instance:
@code
// Show some bullet points at the right
right_column
    *"First-level bullet"
    *"First-level bullet"
    -"Second-level bullet"
@endcode
 * @~french
 * Définit une colonne à droite de la diapositive où placer des puces de textes.
 * Cette colonne sera affichée suivant le thème courant appliqué (par défaut,
 * quelque part à  droite de la diapositive).
 *
 * Par exemple :
@code
// Affiche plusieurs puces de textes à  droite
right_column
    *"Puce de premier niveau"
    *"Puce de premier niveau"
    -"Puce de second niveau"
@endcode
 */
right_column(Body:code);


/**
 * @~english
 * Define a column at the left of the slide where to put images, photos, animations.
 * This column will be displayed according to
 * the current applied theme (by default, somewhere in the left).
 *
 * For instance:
@code
// Show an image at the left
left_column_picture
    image 0, 0, 100%, 100%, "my_image.png"
@endcode
 * @~french
 * Définit une colonne à  gauche de la diapositive où placer images, photos, animations.
 * Cette colonne sera affichée suivant le thème courant appliqué (par défaut,
 * quelque part à  gauche de la diapositive).
 *
 * Par exemple :
@code
// Affiche une image à  gauche
left_column_picture
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 */
left_column_picture(Body:code);


/**
 * @~english
 * Define a column at the right of the slide where to put images, photos, animations.
 * This column will be displayed according to
 * the current applied theme (by default, somewhere in the right).
 *
 * For instance:
@code
// Show an image at the right
right_column_picture
    image 0, 0, 100%, 100%, "my_image.png"
@endcode
 * @~french
 * Définit une colonne à  droite de la diapositive où placer images, photos, animations.
 * Cette colonne sera affichée suivant le thème courant appliqué (par défaut,
 * quelque part à  droite de la diapositive).
 *
 * Par exemple :
@code
// Affiche une image à  droite
right_column_picture
    image 0, 0, 100%, 100%, "mon_image.png"
@endcode
 */
right_column_picture(Body:code);


/**
 * @~english
 * Define a box for an element kind.
 * Draw a box for an element kind of the slide.
 *
 * @p X X-position of the box
 * @p Y Y-position of the box
 * @p W Box width
 * @p H Box height
 * @p Kind Element kind. Typically, it is :
 *   - main_title
 *   - section_title
 *   - title
 *   - subtitle
 *   - picture
 *   - story
 *   - left_column
 *   - right_column
 *   - left_column_picture
 *   - right_column_picture
 *
 * @~french
 * Définit une boite pour un type d'élément.
 * Cette boite sera affichée suivant le thème courant appliqué (par défaut,
 * quelque part à droite de la diapositive).
 *
 * @p X Abscisse de la boite
 * @p Y Ordonnée de la boite
 * @p W Largeur de la boite
 * @p H Longueur de la boite
 * @p Kind Type d'élément. Typiquement, il s'agit de :
 *   - main_title
 *   - section_title
 *   - title
 *   - subtitle
 *   - picture
 *   - story
 *   - left_column
 *   - right_column
 *   - left_column_picture
 *   - right_column_picture
 *
 */
box(X:real, Y:real, W:real, H:real, Kind:text, Body);


/**
 * @~english
 * Display a first-level bullet.
 * @note This is really a normal asterisk character (*). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 *
 * For instance:
@code
// Create a story with first-level bullet
story
    *"First-level bullet"
    *"First-level bullet"
@endcode
 *
 * @~french
 * Affiche une puce de texte de premier niveau.
 * @note Il s'agit d'une astérisque normale (*). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des puces de premier niveau
story
    *"Texte de premier niveau"
    *"Texte de premier niveau"
@endcode
 */
＊(T:text);

/**
 * @~english
 * Display a second-level bullet.
 * @note that this is really a normal minus character (-). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 *
 * For instance:
@code
// Create a story with second-level bullet
story
    *"First-level bullet"
    -"Second-level bullet"
    -"Second-level bullet"
@endcode
 *
 * @~french
 * Affiche une puce de texte de deuxième niveau.
 * @note Il s'agit d'un caractère moins normal (-). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des puces de second niveau
story
    *"Texte de premier niveau"
    -"Texte de second niveau"
    -"Texte de second niveau"
@endcode
 */
‐(T:text);

/**
 * @~english
 * Display a third-level bullet.
 * @note that this is really a normal plus character (+). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 **
 * For instance:
@code
// Create a story with third-level bullet
story
    *"First-level bullet"
    -"Second-level bullet"
    -"Third-level bullet"
@endcode
 *
 * @~french
 * Affiche une puce de texte de troisième niveau.
 * @note Il s'agit d'un caractère plus normal (+). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des puces de troisième niveau
story
    *"Texte de premier niveau"
    -"Texte de second niveau"
    +"Texte de troisième niveau"
@endcode
 */
＋(T:text);


/**
 * @~english
 * Display a first-level text without bullet point.
 * @note This is really a normal asterisk character (*). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 *
 * For instance:
@code
// Create a story with first-level text
story
    !*"First-level bullet"
    !*"First-level bullet"
@endcode
 *
 * @~french
 * Affiche un texte de premier niveau sans puce.
 * @note Il s'agit d'une astérisque normale (*). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des textes de premier niveau sans puces
story
    !*"Texte de premier niveau"
    !*"Texte de premier niveau"
@endcode
 */
!＊(T:text);

/**
 * @~english
 * Display a second-level text without bullet point.
 * @note that this is really a normal minus character (-). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 *
 * For instance:
@code
// Create a story with second-level bullet
story
    !*"First-level text"
    !-"Second-level text"
    !-"Second-level text"
@endcode
 *
 * @~french
 * Affiche un texte de deuxième niveau sans puce.
 * @note Il s'agit d'un caractère moins normal (-). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des textes de second niveau sans puces
story
    !*"Texte de premier niveau"
    !-"Texte de second niveau"
    !-"Texte de second niveau"
@endcode
 */
!‐(T:text);

/**
 * @~english
 * Display a third-level text without bullet point.
 * @note that this is really a normal plus character (+). In this
 * documentation we are using a special unicode character due to
 * technical constraints.
 **
 * For instance:
@code
// Create a story with third-level text
story
    !*"First-level text"
    !-"Second-level text"
    !-"Third-level text"
@endcode
 *
 * @~french
 * Affiche un texte de troisième niveau sans puce.
 * @note Il s'agit d'un caractère plus normal (+). Dans cette documentation
 * nous utilisons un caractère spécial pour des raisons techniques.
 *
 * Par exemple :
@code
// Affiche des textes de troisième niveau sans puces
story
    !*"Texte de premier niveau"
    !-"Texte de second niveau"
    !+"Texte de troisième niveau"
@endcode
 */
!＋(T:text);

/**
 * @~english
 * Set the dimension of the slide.
 * @p Width and @p Height are expressed in pixels.
 * @~french
 * Définit la dimension de la diapositive.
 * @p Width est la largeur et @p Height la hauteur, en pixels.
 */
set_slide_size(Width:real, Height:real);

/**
 * @}
 */
