#!/bin/bash
#
# Copy Tao dependencies into build_root:
#   - DLLs (Qt, msys)
#   - Git

PLUGINS_DIR="$(echo $1 | sed 's@\\@/@g' | sed 's@C:@/c/@g')"

doo() {
  echo $*
  eval $*
}

THISDIR=`dirname $0`

#
# Copy DLLs required by Tao into build_root/
#

(
cd $THISDIR
export PATH=$PATH:.
for f in `bin/ldd build_root/Tao.exe | \
          grep -v -i 'build_root' | \
          grep -v -i 'windows/sys' | \
          grep -v -i 'ntdll.dll' | \
          grep -v -i 'comctl' | \
          sed 's/^.*=> \\(.*\\)(0x.*)$/\\1/' | \
          sed 's@/cygdrive@@'` ; 
do 
    doo cp $f build_root/
done

doo cp -r "${PLUGINS_DIR}"/* build_root/
)


#
# Uncompress Git distribution into build_root/
#

GITKIT=PortableGit-1.7.0.2-preview20100309.7z
(
cd $THISDIR
mkdir -p build_root/git
cd build_root/git
../../bin/7z -y x -bd ../../3rdparty/$GITKIT
)
