#ifndef TAO_MODULE_API_H
#define TAO_MODULE_API_H
// ****************************************************************************
//  module_api.h                                                   Tao project
// ****************************************************************************
//
//   File Description:
//
//    The interface to be implemented by Tao native modules.
//    This file defines the module functions called by the Tao runtime.
//
//
//
//
//
//
// ****************************************************************************
// This document is released under the GNU General Public License.
// See http://www.gnu.org/copyleft/gpl.html and Matthew 25:22 for details
//  (C) 1992-2010 Christophe de Dinechin <christophe@taodyne.com>
//  (C) 2010 Jerome Forissier <jerome@taodyne.com>
//  (C) 2010 Taodyne SAS
// ****************************************************************************


namespace XL
{
    struct Context;
}

namespace Tao
{
    struct ModuleInfo;

    typedef int (*module_init_fn)   (const Tao::ModuleInfo *);
    typedef int (*enter_symbols_fn) (XL::Context *);
    typedef int (*delete_symbols_fn)(XL::Context *);
    typedef int (*module_exit_fn)   (const Tao::ModuleInfo *);
}

extern "C"
{
    // Called once immediately after the module library is loaded
    // [Optional]
    int module_init(const Tao::ModuleInfo *m);

    // Called once after module_init to let the module extend the XL symbol
    // table (for instance, add new XL commands) in a given context
    // [Mandatory: native modules must implement this function]
    // [May be automatically generated by the tbl_gen script]
    int enter_symbols(XL::Context *c);

    // Called once before module is unloaded to let module remove its
    // primitives from the XL symbol table
    // [May be automatically generated by the tbl_gen script]
    int delete_symbols(XL::Context *c);

    // Called when the module library is about to be unloaded
    // [Optional]
    int module_exit(const Tao::ModuleInfo *m);
}

#endif // TAO_MODULE_API_H
